disabled_rules:
  - function_parameter_count
  - identifier_name
  - line_length
  - private_over_fileprivate
  - statement_position
  - todo
  - trailing_comma
  - type_name

opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - OBAKit
  - OBAKitCore
  - TodayView

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - OBAKitCore/Models/Protobuf/gtfs-realtime.pb.swift

file_length:
  warning: 900
  error: 1000

type_body_length:
  warning: 900
  error: 1000
