############
# OneBusAway
############

options:
  bundleIdPrefix: pl.goeuropa.obapb

targets:
  App:
    sources:
      - path: Apps/OBAPB
        name: App
        group: OBAPB
      - path: Apps/Shared/CommonClient
        name: Common
        group: OBAPB
    entitlements:
      path: Apps/OBAPB/OneBusAway.entitlements
      properties:
        com.apple.security.application-groups:
          - group.pl.goeuropa.obapb.iphone
        com.apple.developer.associated-domains:
          - applinks:onebusaway.co
          - applinks:www.onebusaway.co
          - applinks:alerts.onebusaway.org
        com.apple.developer.in-app-payments:
          - merchant.pl.goeuropa.obapb.iphone
    info:
      path: Apps/OBAPB/Info.plist
      properties:
        CFBundleDisplayName: OBAPB
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "obapb", CFBundleURLSchemes: ["obapb"]}]
        LSApplicationQueriesSchemes:
          - fb
          - twitter
          - comgooglemaps
          - fb313213768708402HART
          - org.sdmts.riderapp.compassmobile.payments
          - org.sdmts.pronto
          - co.bytemark.tgt
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains: {
            "onebusaway.co": {
                NSIncludesSubdomains: true,
                NSExceptionAllowsInsecureHTTPLoads: true
            }
          }
        NSHumanReadableCopyright: © Transportation America
        NSUserActivityTypes:
          - pl.goeuropa.obapb.iphone.user_activity.stop
          - pl.goeuropa.obapb.iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: oba@transportationamerica.com
          AppGroup: group.pl.goeuropa.obapb.iphone
          BundledRegionsFileName: regions.json
          Donations:
            Enabled: false
            DonationManagementPortal: "https://onebusaway.co/manage-donations"
          ExtensionURLScheme: obapb
          PrivacyPolicyURL: https://onebusaway.org/privacy/
          PushNotificationAPIKey: d5d0d28a-6091-46cd-9627-0ce01ffa9f9e
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: https://data.tracktrolley.com
          RegionsServerAPIPath: /regions-obapb.json
    settings:
      base:
        DEVELOPMENT_TEAM: 85APG5FQFE
        PRODUCT_BUNDLE_IDENTIFIER: pl.goeuropa.obapb.iphone
  TodayView:
    sources: ["Apps/OBAPB/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.pl.goeuropa.obapb.iphone
    info:
      properties:
        CFBundleDisplayName: OBAPB
        OBAKitConfig:
          AppGroup: group.pl.goeuropa.obapb.iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: obapb
          RESTServerAPIKey: pl.goeuropa.obapby.iphone
          RegionsServerBaseAddress: https://data.tracktrolley.com
          RegionsServerAPIPath: /regions-obapb.json
    settings:
      base:
        DEVELOPMENT_TEAM: 85APG5FQFE
        PRODUCT_BUNDLE_IDENTIFIER: pl.goeuropa.obapb.iphone.TodayView
  OBAWidget:
    sources: ["Apps/OBAPB/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.pl.goeuropa.obapb.iphone
    info:
      properties:
        CFBundleDisplayName: OBAPB
        OBAKitConfig:
          AppGroup: group.pl.goeuropa.obapb.iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: obapb
          RESTServerAPIKey: pl.goeuropa.obapb.iphone
          RegionsServerBaseAddress: https://data.tracktrolley.com
          RegionsServerAPIPath: /regions-obapb.json
    settings:
      base:
        DEVELOPMENT_TEAM: 85APG5FQFE
        PRODUCT_BUNDLE_IDENTIFIER: pl.goeuropa.obapb.iphone.OBAWidget
include:
  - path: Apps/Shared/app_shared.yml
  - path: Apps/Shared/analytics_fx_config.yml
  - path: Apps/Shared/push_config.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
  - path: OBAWidget/project.yml
