############
# OneBusAway
############

options:
  bundleIdPrefix: pl.goeuropa.obata

targets:
  App:
    sources:
      - path: Apps/OBATA
        name: App
        group: OBATA
      - path: Apps/Shared/Analytics
        name: Analytics
        group: OBATA
      - path: Apps/Shared/CommonClient
        name: Common
        group: OBATA
      - path: Apps/Shared/OneSignal
        name: OneSignal
        group: OBATA
    dependencies:
      - package: OneSignal
    entitlements:
      path: Apps/OBATA/OBATA.entitlements
      properties:
        com.apple.security.application-groups:
          - group.pl.goeuropa.obata.iphone
        com.apple.developer.associated-domains:
          - applinks:onebusaway.co
          - applinks:www.onebusaway.co
          - applinks:alerts.onebusaway.org
    info:
      path: Apps/OBATA/Info.plist
      properties:
        CFBundleDisplayName: OBATA
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "obata", CFBundleURLSchemes: ["obata"]}]
        LSApplicationQueriesSchemes:
          - fb
          - twitter
          - comgooglemaps
          - fb313213768708402HART
          - org.sdmts.riderapp.compassmobile.payments
          - org.sdmts.pronto
          - co.bytemark.tgt
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains: {
            "onebusaway.co": {
                NSIncludesSubdomains: true,
                NSExceptionAllowsInsecureHTTPLoads: true
            }
          }
        NSHumanReadableCopyright: © Open Transit Software Foundation
        NSUserActivityTypes:
          - pl.goeuropa.obata.iphone.user_activity.stop
          - pl.goeuropa.obata.iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: oba@transportationamerica.com
          AppGroup: group.pl.goeuropa.obata.iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: obata
          PrivacyPolicyURL: https://onebusaway.org/privacy/
          PushNotificationAPIKey: d5d0d28a-6091-46cd-9627-0ce01ffa9f9e
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: https://data.tracktrolley.com
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 85APG5FQFE
        PRODUCT_BUNDLE_IDENTIFIER: pl.goeuropa.obata.iphone
  TodayView:
    sources: ["Apps/OBATA/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.pl.goeuropa.obata.iphone
    info:
      properties:
        CFBundleDisplayName: OBATA
        OBAKitConfig:
          AppGroup: group.pl.goeuropa.obata.iphone
          BundledRegionsFileName: regions.json
          DeepLinkServerBaseAddress: https://onebusaway.co
          ExtensionURLScheme: obata
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: https://data.tracktrolley.com
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 85APG5FQFE
        PRODUCT_BUNDLE_IDENTIFIER: pl.goeuropa.obata.iphone.TodayView

include:
  - path: Apps/Shared/app_shared.yml
  - path: Apps/Shared/analytics_fx_config.yml
  - path: Apps/Shared/push_config.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
